artifacts_root: artifacts # Path to the root directory where all the artifacts will be stored

# Data ingestion configuration
data_ingestion: 
  root_dir: artifacts/data_ingestion # Path to the root directory where the data will be stored
  source_URL: https://github.com/trolex213/chickendiseasedataset/raw/main/Chicken-fecal-images.zip # URL from where the data will be downloaded
  local_data_file: artifacts/data_ingestion/data.zip # Path to the local file where the zipped dataset will be saved
  unzip_dir: artifacts/data_ingestion/unzipped_data # Path to the directory where the unzipped data will be stored

prepare_base_model:
  root_dir: artifacts/prepare_base_model # Path to the root directory where the base model will be stored
  base_model_path: artifacts/prepare_base_model/base_model.h5 # Path to the base model file
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5 # Path to the updated base model file